#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OTA")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertreceptionist(receptionist instance);
  partial void Updatereceptionist(receptionist instance);
  partial void Deletereceptionist(receptionist instance);
  partial void Insertsupervisor(supervisor instance);
  partial void Updatesupervisor(supervisor instance);
  partial void Deletesupervisor(supervisor instance);
  partial void Insertlap_model(lap_model instance);
  partial void Updatelap_model(lap_model instance);
  partial void Deletelap_model(lap_model instance);
  partial void Insertcustomer(customer instance);
  partial void Updatecustomer(customer instance);
  partial void Deletecustomer(customer instance);
  partial void Insertreception(reception instance);
  partial void Updatereception(reception instance);
  partial void Deletereception(reception instance);
  partial void InsertProblem(Problem instance);
  partial void UpdateProblem(Problem instance);
  partial void DeleteProblem(Problem instance);
  partial void Insertlaptop(laptop instance);
  partial void Updatelaptop(laptop instance);
  partial void Deletelaptop(laptop instance);
  partial void Insertstaff(staff instance);
  partial void Updatestaff(staff instance);
  partial void Deletestaff(staff instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OTAConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<manager> managers
	{
		get
		{
			return this.GetTable<manager>();
		}
	}
	
	public System.Data.Linq.Table<receptionist> receptionists
	{
		get
		{
			return this.GetTable<receptionist>();
		}
	}
	
	public System.Data.Linq.Table<supervisor> supervisors
	{
		get
		{
			return this.GetTable<supervisor>();
		}
	}
	
	public System.Data.Linq.Table<lap_model> lap_models
	{
		get
		{
			return this.GetTable<lap_model>();
		}
	}
	
	public System.Data.Linq.Table<sup_form> sup_forms
	{
		get
		{
			return this.GetTable<sup_form>();
		}
	}
	
	public System.Data.Linq.Table<customer> customers
	{
		get
		{
			return this.GetTable<customer>();
		}
	}
	
	public System.Data.Linq.Table<reception> receptions
	{
		get
		{
			return this.GetTable<reception>();
		}
	}
	
	public System.Data.Linq.Table<Problem> Problems
	{
		get
		{
			return this.GetTable<Problem>();
		}
	}
	
	public System.Data.Linq.Table<laptop> laptops
	{
		get
		{
			return this.GetTable<laptop>();
		}
	}
	
	public System.Data.Linq.Table<lap_prob> lap_probs
	{
		get
		{
			return this.GetTable<lap_prob>();
		}
	}
	
	public System.Data.Linq.Table<st_form> st_forms
	{
		get
		{
			return this.GetTable<st_form>();
		}
	}
	
	public System.Data.Linq.Table<staff> staffs
	{
		get
		{
			return this.GetTable<staff>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.validmanageruserpass")]
	public ISingleResult<validmanageruserpassResult> validmanageruserpass([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user, pass);
		return ((ISingleResult<validmanageruserpassResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.validstaffuserpass")]
	public ISingleResult<validstaffuserpassResult> validstaffuserpass([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user, pass);
		return ((ISingleResult<validstaffuserpassResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.validsupervisoruserpass")]
	public ISingleResult<validsupervisoruserpassResult> validsupervisoruserpass([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user, pass);
		return ((ISingleResult<validsupervisoruserpassResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.validreceptionistuserpass")]
	public ISingleResult<validreceptionistuserpassResult> validreceptionistuserpass([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user, pass);
		return ((ISingleResult<validreceptionistuserpassResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertsupform")]
	public int insertsupform([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> rcode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1)")] string sdesc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sid)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rcode, sdesc, sid);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deletenullfromlapprob")]
	public int deletenullfromlapprob([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string lapser)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lapser);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertstform")]
	public int insertstform([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> rcode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(300)")] string stdesc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> stid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> stdate)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rcode, stdesc, stid, stdate);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updatelapprobfinish")]
	public int updatelapprobfinish([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string lapser, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> finishtime)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lapser, pid, finishtime);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updatelapprobstart")]
	public int updatelapprobstart([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string lapser, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> starttime)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lapser, pid, starttime);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updatestformstaffdesc")]
	public int updatestformstaffdesc([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reccode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(300)")] string stdesc)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reccode, stdesc);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertlapprob")]
	public int insertlapprob([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string lapser, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> sdtime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fdtime)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lapser, pid, sdtime, fdtime);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updatelapprobfix")]
	public int updatelapprobfix([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string lapser, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> fix)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lapser, pid, fix);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updatestformstafflasttime")]
	public int updatestformstafflasttime([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reccode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> stlasttime)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reccode, stlasttime);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.selectpoints", IsComposable=true)]
	public object selectpoints([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> stid)
	{
		return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), stid).ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.managers")]
public partial class manager
{
	
	private int _mng_id;
	
	private string _mng_fname;
	
	private string _mng_lname;
	
	private string _mng_user;
	
	private string _mng_pass;
	
	public manager()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mng_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int mng_id
	{
		get
		{
			return this._mng_id;
		}
		set
		{
			if ((this._mng_id != value))
			{
				this._mng_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mng_fname", DbType="NVarChar(50)")]
	public string mng_fname
	{
		get
		{
			return this._mng_fname;
		}
		set
		{
			if ((this._mng_fname != value))
			{
				this._mng_fname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mng_lname", DbType="NVarChar(50)")]
	public string mng_lname
	{
		get
		{
			return this._mng_lname;
		}
		set
		{
			if ((this._mng_lname != value))
			{
				this._mng_lname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mng_user", DbType="NVarChar(50)")]
	public string mng_user
	{
		get
		{
			return this._mng_user;
		}
		set
		{
			if ((this._mng_user != value))
			{
				this._mng_user = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mng_pass", DbType="NVarChar(50)")]
	public string mng_pass
	{
		get
		{
			return this._mng_pass;
		}
		set
		{
			if ((this._mng_pass != value))
			{
				this._mng_pass = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.receptionist")]
public partial class receptionist : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _recep_id;
	
	private string _recep_fname;
	
	private string _recep_lname;
	
	private string _recep_tel;
	
	private string _recep_mob;
	
	private string _recep_add;
	
	private string _recep_user;
	
	private string _recep_pass;
	
	private EntitySet<reception> _receptions;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrecep_idChanging(int value);
    partial void Onrecep_idChanged();
    partial void Onrecep_fnameChanging(string value);
    partial void Onrecep_fnameChanged();
    partial void Onrecep_lnameChanging(string value);
    partial void Onrecep_lnameChanged();
    partial void Onrecep_telChanging(string value);
    partial void Onrecep_telChanged();
    partial void Onrecep_mobChanging(string value);
    partial void Onrecep_mobChanged();
    partial void Onrecep_addChanging(string value);
    partial void Onrecep_addChanged();
    partial void Onrecep_userChanging(string value);
    partial void Onrecep_userChanged();
    partial void Onrecep_passChanging(string value);
    partial void Onrecep_passChanged();
    #endregion
	
	public receptionist()
	{
		this._receptions = new EntitySet<reception>(new Action<reception>(this.attach_receptions), new Action<reception>(this.detach_receptions));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recep_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int recep_id
	{
		get
		{
			return this._recep_id;
		}
		set
		{
			if ((this._recep_id != value))
			{
				this.Onrecep_idChanging(value);
				this.SendPropertyChanging();
				this._recep_id = value;
				this.SendPropertyChanged("recep_id");
				this.Onrecep_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recep_fname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string recep_fname
	{
		get
		{
			return this._recep_fname;
		}
		set
		{
			if ((this._recep_fname != value))
			{
				this.Onrecep_fnameChanging(value);
				this.SendPropertyChanging();
				this._recep_fname = value;
				this.SendPropertyChanged("recep_fname");
				this.Onrecep_fnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recep_lname", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string recep_lname
	{
		get
		{
			return this._recep_lname;
		}
		set
		{
			if ((this._recep_lname != value))
			{
				this.Onrecep_lnameChanging(value);
				this.SendPropertyChanging();
				this._recep_lname = value;
				this.SendPropertyChanged("recep_lname");
				this.Onrecep_lnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recep_tel", DbType="NVarChar(20)")]
	public string recep_tel
	{
		get
		{
			return this._recep_tel;
		}
		set
		{
			if ((this._recep_tel != value))
			{
				this.Onrecep_telChanging(value);
				this.SendPropertyChanging();
				this._recep_tel = value;
				this.SendPropertyChanged("recep_tel");
				this.Onrecep_telChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recep_mob", DbType="NVarChar(20)")]
	public string recep_mob
	{
		get
		{
			return this._recep_mob;
		}
		set
		{
			if ((this._recep_mob != value))
			{
				this.Onrecep_mobChanging(value);
				this.SendPropertyChanging();
				this._recep_mob = value;
				this.SendPropertyChanged("recep_mob");
				this.Onrecep_mobChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recep_add", DbType="NVarChar(300)")]
	public string recep_add
	{
		get
		{
			return this._recep_add;
		}
		set
		{
			if ((this._recep_add != value))
			{
				this.Onrecep_addChanging(value);
				this.SendPropertyChanging();
				this._recep_add = value;
				this.SendPropertyChanged("recep_add");
				this.Onrecep_addChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recep_user", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string recep_user
	{
		get
		{
			return this._recep_user;
		}
		set
		{
			if ((this._recep_user != value))
			{
				this.Onrecep_userChanging(value);
				this.SendPropertyChanging();
				this._recep_user = value;
				this.SendPropertyChanged("recep_user");
				this.Onrecep_userChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recep_pass", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string recep_pass
	{
		get
		{
			return this._recep_pass;
		}
		set
		{
			if ((this._recep_pass != value))
			{
				this.Onrecep_passChanging(value);
				this.SendPropertyChanging();
				this._recep_pass = value;
				this.SendPropertyChanged("recep_pass");
				this.Onrecep_passChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="receptionist_reception", Storage="_receptions", ThisKey="recep_id", OtherKey="recep_id")]
	public EntitySet<reception> receptions
	{
		get
		{
			return this._receptions;
		}
		set
		{
			this._receptions.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_receptions(reception entity)
	{
		this.SendPropertyChanging();
		entity.receptionist = this;
	}
	
	private void detach_receptions(reception entity)
	{
		this.SendPropertyChanging();
		entity.receptionist = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.supervisor")]
public partial class supervisor : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _sup_id;
	
	private string _sup_fname;
	
	private string _sup_lname;
	
	private string _sup_tel;
	
	private string _sup_mob;
	
	private string _sup_add;
	
	private string _sup_user;
	
	private string _sup_pass;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsup_idChanging(int value);
    partial void Onsup_idChanged();
    partial void Onsup_fnameChanging(string value);
    partial void Onsup_fnameChanged();
    partial void Onsup_lnameChanging(string value);
    partial void Onsup_lnameChanged();
    partial void Onsup_telChanging(string value);
    partial void Onsup_telChanged();
    partial void Onsup_mobChanging(string value);
    partial void Onsup_mobChanged();
    partial void Onsup_addChanging(string value);
    partial void Onsup_addChanged();
    partial void Onsup_userChanging(string value);
    partial void Onsup_userChanged();
    partial void Onsup_passChanging(string value);
    partial void Onsup_passChanged();
    #endregion
	
	public supervisor()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sup_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int sup_id
	{
		get
		{
			return this._sup_id;
		}
		set
		{
			if ((this._sup_id != value))
			{
				this.Onsup_idChanging(value);
				this.SendPropertyChanging();
				this._sup_id = value;
				this.SendPropertyChanged("sup_id");
				this.Onsup_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sup_fname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string sup_fname
	{
		get
		{
			return this._sup_fname;
		}
		set
		{
			if ((this._sup_fname != value))
			{
				this.Onsup_fnameChanging(value);
				this.SendPropertyChanging();
				this._sup_fname = value;
				this.SendPropertyChanged("sup_fname");
				this.Onsup_fnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sup_lname", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string sup_lname
	{
		get
		{
			return this._sup_lname;
		}
		set
		{
			if ((this._sup_lname != value))
			{
				this.Onsup_lnameChanging(value);
				this.SendPropertyChanging();
				this._sup_lname = value;
				this.SendPropertyChanged("sup_lname");
				this.Onsup_lnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sup_tel", DbType="NVarChar(20)")]
	public string sup_tel
	{
		get
		{
			return this._sup_tel;
		}
		set
		{
			if ((this._sup_tel != value))
			{
				this.Onsup_telChanging(value);
				this.SendPropertyChanging();
				this._sup_tel = value;
				this.SendPropertyChanged("sup_tel");
				this.Onsup_telChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sup_mob", DbType="NVarChar(20)")]
	public string sup_mob
	{
		get
		{
			return this._sup_mob;
		}
		set
		{
			if ((this._sup_mob != value))
			{
				this.Onsup_mobChanging(value);
				this.SendPropertyChanging();
				this._sup_mob = value;
				this.SendPropertyChanged("sup_mob");
				this.Onsup_mobChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sup_add", DbType="NVarChar(300)")]
	public string sup_add
	{
		get
		{
			return this._sup_add;
		}
		set
		{
			if ((this._sup_add != value))
			{
				this.Onsup_addChanging(value);
				this.SendPropertyChanging();
				this._sup_add = value;
				this.SendPropertyChanged("sup_add");
				this.Onsup_addChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sup_user", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string sup_user
	{
		get
		{
			return this._sup_user;
		}
		set
		{
			if ((this._sup_user != value))
			{
				this.Onsup_userChanging(value);
				this.SendPropertyChanging();
				this._sup_user = value;
				this.SendPropertyChanged("sup_user");
				this.Onsup_userChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sup_pass", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string sup_pass
	{
		get
		{
			return this._sup_pass;
		}
		set
		{
			if ((this._sup_pass != value))
			{
				this.Onsup_passChanging(value);
				this.SendPropertyChanging();
				this._sup_pass = value;
				this.SendPropertyChanged("sup_pass");
				this.Onsup_passChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lap_models")]
public partial class lap_model : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _mod_id;
	
	private string _model;
	
	private EntitySet<laptop> _laptops;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmod_idChanging(int value);
    partial void Onmod_idChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    #endregion
	
	public lap_model()
	{
		this._laptops = new EntitySet<laptop>(new Action<laptop>(this.attach_laptops), new Action<laptop>(this.detach_laptops));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mod_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int mod_id
	{
		get
		{
			return this._mod_id;
		}
		set
		{
			if ((this._mod_id != value))
			{
				this.Onmod_idChanging(value);
				this.SendPropertyChanging();
				this._mod_id = value;
				this.SendPropertyChanged("mod_id");
				this.Onmod_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="NVarChar(50)")]
	public string model
	{
		get
		{
			return this._model;
		}
		set
		{
			if ((this._model != value))
			{
				this.OnmodelChanging(value);
				this.SendPropertyChanging();
				this._model = value;
				this.SendPropertyChanged("model");
				this.OnmodelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lap_model_laptop", Storage="_laptops", ThisKey="mod_id", OtherKey="lap_model")]
	public EntitySet<laptop> laptops
	{
		get
		{
			return this._laptops;
		}
		set
		{
			this._laptops.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_laptops(laptop entity)
	{
		this.SendPropertyChanging();
		entity.lap_model1 = this;
	}
	
	private void detach_laptops(laptop entity)
	{
		this.SendPropertyChanging();
		entity.lap_model1 = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sup_form")]
public partial class sup_form
{
	
	private int _rec_code;
	
	private string _sup_desc;
	
	private int _sup_id;
	
	public sup_form()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rec_code", DbType="Int NOT NULL")]
	public int rec_code
	{
		get
		{
			return this._rec_code;
		}
		set
		{
			if ((this._rec_code != value))
			{
				this._rec_code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sup_desc", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
	public string sup_desc
	{
		get
		{
			return this._sup_desc;
		}
		set
		{
			if ((this._sup_desc != value))
			{
				this._sup_desc = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sup_id", DbType="Int NOT NULL")]
	public int sup_id
	{
		get
		{
			return this._sup_id;
		}
		set
		{
			if ((this._sup_id != value))
			{
				this._sup_id = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.customers")]
public partial class customer : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _cust_id;
	
	private string _cust_fname;
	
	private string _cust_lname;
	
	private string _cust_tel;
	
	private string _cust_mob;
	
	private string _lap_serial;
	
	private EntityRef<laptop> _laptop;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncust_idChanging(int value);
    partial void Oncust_idChanged();
    partial void Oncust_fnameChanging(string value);
    partial void Oncust_fnameChanged();
    partial void Oncust_lnameChanging(string value);
    partial void Oncust_lnameChanged();
    partial void Oncust_telChanging(string value);
    partial void Oncust_telChanged();
    partial void Oncust_mobChanging(string value);
    partial void Oncust_mobChanged();
    partial void Onlap_serialChanging(string value);
    partial void Onlap_serialChanged();
    #endregion
	
	public customer()
	{
		this._laptop = default(EntityRef<laptop>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int cust_id
	{
		get
		{
			return this._cust_id;
		}
		set
		{
			if ((this._cust_id != value))
			{
				this.Oncust_idChanging(value);
				this.SendPropertyChanging();
				this._cust_id = value;
				this.SendPropertyChanged("cust_id");
				this.Oncust_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_fname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string cust_fname
	{
		get
		{
			return this._cust_fname;
		}
		set
		{
			if ((this._cust_fname != value))
			{
				this.Oncust_fnameChanging(value);
				this.SendPropertyChanging();
				this._cust_fname = value;
				this.SendPropertyChanged("cust_fname");
				this.Oncust_fnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_lname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string cust_lname
	{
		get
		{
			return this._cust_lname;
		}
		set
		{
			if ((this._cust_lname != value))
			{
				this.Oncust_lnameChanging(value);
				this.SendPropertyChanging();
				this._cust_lname = value;
				this.SendPropertyChanged("cust_lname");
				this.Oncust_lnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_tel", DbType="NVarChar(20)")]
	public string cust_tel
	{
		get
		{
			return this._cust_tel;
		}
		set
		{
			if ((this._cust_tel != value))
			{
				this.Oncust_telChanging(value);
				this.SendPropertyChanging();
				this._cust_tel = value;
				this.SendPropertyChanged("cust_tel");
				this.Oncust_telChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_mob", DbType="NVarChar(20)")]
	public string cust_mob
	{
		get
		{
			return this._cust_mob;
		}
		set
		{
			if ((this._cust_mob != value))
			{
				this.Oncust_mobChanging(value);
				this.SendPropertyChanging();
				this._cust_mob = value;
				this.SendPropertyChanged("cust_mob");
				this.Oncust_mobChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lap_serial", DbType="NVarChar(20)")]
	public string lap_serial
	{
		get
		{
			return this._lap_serial;
		}
		set
		{
			if ((this._lap_serial != value))
			{
				if (this._laptop.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onlap_serialChanging(value);
				this.SendPropertyChanging();
				this._lap_serial = value;
				this.SendPropertyChanged("lap_serial");
				this.Onlap_serialChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="laptop_customer", Storage="_laptop", ThisKey="lap_serial", OtherKey="lap_serial", IsForeignKey=true, DeleteRule="CASCADE")]
	public laptop laptop
	{
		get
		{
			return this._laptop.Entity;
		}
		set
		{
			laptop previousValue = this._laptop.Entity;
			if (((previousValue != value) 
						|| (this._laptop.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._laptop.Entity = null;
					previousValue.customers.Remove(this);
				}
				this._laptop.Entity = value;
				if ((value != null))
				{
					value.customers.Add(this);
					this._lap_serial = value.lap_serial;
				}
				else
				{
					this._lap_serial = default(string);
				}
				this.SendPropertyChanged("laptop");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.receptions")]
public partial class reception : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _rec_code;
	
	private string _lap_serial;
	
	private int _recep_id;
	
	private string _recep_desc;
	
	private System.Nullable<System.DateTime> _rec_date;
	
	private EntityRef<receptionist> _receptionist;
	
	private EntityRef<laptop> _laptop;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrec_codeChanging(int value);
    partial void Onrec_codeChanged();
    partial void Onlap_serialChanging(string value);
    partial void Onlap_serialChanged();
    partial void Onrecep_idChanging(int value);
    partial void Onrecep_idChanged();
    partial void Onrecep_descChanging(string value);
    partial void Onrecep_descChanged();
    partial void Onrec_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onrec_dateChanged();
    #endregion
	
	public reception()
	{
		this._receptionist = default(EntityRef<receptionist>);
		this._laptop = default(EntityRef<laptop>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rec_code", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int rec_code
	{
		get
		{
			return this._rec_code;
		}
		set
		{
			if ((this._rec_code != value))
			{
				this.Onrec_codeChanging(value);
				this.SendPropertyChanging();
				this._rec_code = value;
				this.SendPropertyChanged("rec_code");
				this.Onrec_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lap_serial", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string lap_serial
	{
		get
		{
			return this._lap_serial;
		}
		set
		{
			if ((this._lap_serial != value))
			{
				if (this._laptop.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onlap_serialChanging(value);
				this.SendPropertyChanging();
				this._lap_serial = value;
				this.SendPropertyChanged("lap_serial");
				this.Onlap_serialChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recep_id", DbType="Int NOT NULL")]
	public int recep_id
	{
		get
		{
			return this._recep_id;
		}
		set
		{
			if ((this._recep_id != value))
			{
				if (this._receptionist.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onrecep_idChanging(value);
				this.SendPropertyChanging();
				this._recep_id = value;
				this.SendPropertyChanged("recep_id");
				this.Onrecep_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recep_desc", DbType="NVarChar(300)")]
	public string recep_desc
	{
		get
		{
			return this._recep_desc;
		}
		set
		{
			if ((this._recep_desc != value))
			{
				this.Onrecep_descChanging(value);
				this.SendPropertyChanging();
				this._recep_desc = value;
				this.SendPropertyChanged("recep_desc");
				this.Onrecep_descChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rec_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> rec_date
	{
		get
		{
			return this._rec_date;
		}
		set
		{
			if ((this._rec_date != value))
			{
				this.Onrec_dateChanging(value);
				this.SendPropertyChanging();
				this._rec_date = value;
				this.SendPropertyChanged("rec_date");
				this.Onrec_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="receptionist_reception", Storage="_receptionist", ThisKey="recep_id", OtherKey="recep_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public receptionist receptionist
	{
		get
		{
			return this._receptionist.Entity;
		}
		set
		{
			receptionist previousValue = this._receptionist.Entity;
			if (((previousValue != value) 
						|| (this._receptionist.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._receptionist.Entity = null;
					previousValue.receptions.Remove(this);
				}
				this._receptionist.Entity = value;
				if ((value != null))
				{
					value.receptions.Add(this);
					this._recep_id = value.recep_id;
				}
				else
				{
					this._recep_id = default(int);
				}
				this.SendPropertyChanged("receptionist");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="laptop_reception", Storage="_laptop", ThisKey="lap_serial", OtherKey="lap_serial", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public laptop laptop
	{
		get
		{
			return this._laptop.Entity;
		}
		set
		{
			laptop previousValue = this._laptop.Entity;
			if (((previousValue != value) 
						|| (this._laptop.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._laptop.Entity = null;
					previousValue.receptions.Remove(this);
				}
				this._laptop.Entity = value;
				if ((value != null))
				{
					value.receptions.Add(this);
					this._lap_serial = value.lap_serial;
				}
				else
				{
					this._lap_serial = default(string);
				}
				this.SendPropertyChanged("laptop");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Problems")]
public partial class Problem : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _prob_id;
	
	private string _prob_title;
	
	private string _prob_time;
	
	private System.Nullable<int> _prob_point;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprob_idChanging(int value);
    partial void Onprob_idChanged();
    partial void Onprob_titleChanging(string value);
    partial void Onprob_titleChanged();
    partial void Onprob_timeChanging(string value);
    partial void Onprob_timeChanged();
    partial void Onprob_pointChanging(System.Nullable<int> value);
    partial void Onprob_pointChanged();
    #endregion
	
	public Problem()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prob_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int prob_id
	{
		get
		{
			return this._prob_id;
		}
		set
		{
			if ((this._prob_id != value))
			{
				this.Onprob_idChanging(value);
				this.SendPropertyChanging();
				this._prob_id = value;
				this.SendPropertyChanged("prob_id");
				this.Onprob_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prob_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string prob_title
	{
		get
		{
			return this._prob_title;
		}
		set
		{
			if ((this._prob_title != value))
			{
				this.Onprob_titleChanging(value);
				this.SendPropertyChanging();
				this._prob_title = value;
				this.SendPropertyChanged("prob_title");
				this.Onprob_titleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prob_time", DbType="NVarChar(50)")]
	public string prob_time
	{
		get
		{
			return this._prob_time;
		}
		set
		{
			if ((this._prob_time != value))
			{
				this.Onprob_timeChanging(value);
				this.SendPropertyChanging();
				this._prob_time = value;
				this.SendPropertyChanged("prob_time");
				this.Onprob_timeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prob_point", DbType="Int")]
	public System.Nullable<int> prob_point
	{
		get
		{
			return this._prob_point;
		}
		set
		{
			if ((this._prob_point != value))
			{
				this.Onprob_pointChanging(value);
				this.SendPropertyChanging();
				this._prob_point = value;
				this.SendPropertyChanged("prob_point");
				this.Onprob_pointChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.laptop")]
public partial class laptop : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _lap_serial;
	
	private System.Nullable<int> _lap_model;
	
	private System.Nullable<bool> _fixed;
	
	private string _lap_se;
	
	private EntitySet<customer> _customers;
	
	private EntitySet<reception> _receptions;
	
	private EntityRef<lap_model> _lap_model1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlap_serialChanging(string value);
    partial void Onlap_serialChanged();
    partial void Onlap_modelChanging(System.Nullable<int> value);
    partial void Onlap_modelChanged();
    partial void OnfixedChanging(System.Nullable<bool> value);
    partial void OnfixedChanged();
    partial void Onlap_seChanging(string value);
    partial void Onlap_seChanged();
    #endregion
	
	public laptop()
	{
		this._customers = new EntitySet<customer>(new Action<customer>(this.attach_customers), new Action<customer>(this.detach_customers));
		this._receptions = new EntitySet<reception>(new Action<reception>(this.attach_receptions), new Action<reception>(this.detach_receptions));
		this._lap_model1 = default(EntityRef<lap_model>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lap_serial", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string lap_serial
	{
		get
		{
			return this._lap_serial;
		}
		set
		{
			if ((this._lap_serial != value))
			{
				this.Onlap_serialChanging(value);
				this.SendPropertyChanging();
				this._lap_serial = value;
				this.SendPropertyChanged("lap_serial");
				this.Onlap_serialChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lap_model", DbType="Int")]
	public System.Nullable<int> lap_model
	{
		get
		{
			return this._lap_model;
		}
		set
		{
			if ((this._lap_model != value))
			{
				if (this._lap_model1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onlap_modelChanging(value);
				this.SendPropertyChanging();
				this._lap_model = value;
				this.SendPropertyChanged("lap_model");
				this.Onlap_modelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="fixed", Storage="_fixed", DbType="Bit")]
	public System.Nullable<bool> @fixed
	{
		get
		{
			return this._fixed;
		}
		set
		{
			if ((this._fixed != value))
			{
				this.OnfixedChanging(value);
				this.SendPropertyChanging();
				this._fixed = value;
				this.SendPropertyChanged("@fixed");
				this.OnfixedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lap_se", DbType="NVarChar(20)")]
	public string lap_se
	{
		get
		{
			return this._lap_se;
		}
		set
		{
			if ((this._lap_se != value))
			{
				this.Onlap_seChanging(value);
				this.SendPropertyChanging();
				this._lap_se = value;
				this.SendPropertyChanged("lap_se");
				this.Onlap_seChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="laptop_customer", Storage="_customers", ThisKey="lap_serial", OtherKey="lap_serial")]
	public EntitySet<customer> customers
	{
		get
		{
			return this._customers;
		}
		set
		{
			this._customers.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="laptop_reception", Storage="_receptions", ThisKey="lap_serial", OtherKey="lap_serial")]
	public EntitySet<reception> receptions
	{
		get
		{
			return this._receptions;
		}
		set
		{
			this._receptions.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lap_model_laptop", Storage="_lap_model1", ThisKey="lap_model", OtherKey="mod_id", IsForeignKey=true, DeleteRule="SET NULL")]
	public lap_model lap_model1
	{
		get
		{
			return this._lap_model1.Entity;
		}
		set
		{
			lap_model previousValue = this._lap_model1.Entity;
			if (((previousValue != value) 
						|| (this._lap_model1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._lap_model1.Entity = null;
					previousValue.laptops.Remove(this);
				}
				this._lap_model1.Entity = value;
				if ((value != null))
				{
					value.laptops.Add(this);
					this._lap_model = value.mod_id;
				}
				else
				{
					this._lap_model = default(Nullable<int>);
				}
				this.SendPropertyChanged("lap_model1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_customers(customer entity)
	{
		this.SendPropertyChanging();
		entity.laptop = this;
	}
	
	private void detach_customers(customer entity)
	{
		this.SendPropertyChanging();
		entity.laptop = null;
	}
	
	private void attach_receptions(reception entity)
	{
		this.SendPropertyChanging();
		entity.laptop = this;
	}
	
	private void detach_receptions(reception entity)
	{
		this.SendPropertyChanging();
		entity.laptop = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lap_prob")]
public partial class lap_prob
{
	
	private string _lap_serial;
	
	private System.Nullable<int> _prob_id;
	
	private System.Nullable<System.DateTime> _lapprob_starttime;
	
	private System.Nullable<System.DateTime> _lapprob_finishtime;
	
	private System.Nullable<int> _lapprob_fix;
	
	public lap_prob()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lap_serial", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string lap_serial
	{
		get
		{
			return this._lap_serial;
		}
		set
		{
			if ((this._lap_serial != value))
			{
				this._lap_serial = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prob_id", DbType="Int")]
	public System.Nullable<int> prob_id
	{
		get
		{
			return this._prob_id;
		}
		set
		{
			if ((this._prob_id != value))
			{
				this._prob_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lapprob_starttime", DbType="DateTime2")]
	public System.Nullable<System.DateTime> lapprob_starttime
	{
		get
		{
			return this._lapprob_starttime;
		}
		set
		{
			if ((this._lapprob_starttime != value))
			{
				this._lapprob_starttime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lapprob_finishtime", DbType="DateTime2")]
	public System.Nullable<System.DateTime> lapprob_finishtime
	{
		get
		{
			return this._lapprob_finishtime;
		}
		set
		{
			if ((this._lapprob_finishtime != value))
			{
				this._lapprob_finishtime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lapprob_fix", DbType="Int")]
	public System.Nullable<int> lapprob_fix
	{
		get
		{
			return this._lapprob_fix;
		}
		set
		{
			if ((this._lapprob_fix != value))
			{
				this._lapprob_fix = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.st_form")]
public partial class st_form
{
	
	private int _rec_code;
	
	private string _st_desc;
	
	private System.Nullable<int> _st_id;
	
	private System.Nullable<System.DateTime> _st_lasttime;
	
	public st_form()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rec_code", DbType="Int NOT NULL")]
	public int rec_code
	{
		get
		{
			return this._rec_code;
		}
		set
		{
			if ((this._rec_code != value))
			{
				this._rec_code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_desc", DbType="NVarChar(300)")]
	public string st_desc
	{
		get
		{
			return this._st_desc;
		}
		set
		{
			if ((this._st_desc != value))
			{
				this._st_desc = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_id", DbType="Int")]
	public System.Nullable<int> st_id
	{
		get
		{
			return this._st_id;
		}
		set
		{
			if ((this._st_id != value))
			{
				this._st_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_lasttime", DbType="DateTime2")]
	public System.Nullable<System.DateTime> st_lasttime
	{
		get
		{
			return this._st_lasttime;
		}
		set
		{
			if ((this._st_lasttime != value))
			{
				this._st_lasttime = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.staff")]
public partial class staff : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _st_id;
	
	private string _st_fname;
	
	private string _st_lname;
	
	private string _st_tel;
	
	private string _st_mob;
	
	private string _st_add;
	
	private string _st_user;
	
	private string _st_pass;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onst_idChanging(int value);
    partial void Onst_idChanged();
    partial void Onst_fnameChanging(string value);
    partial void Onst_fnameChanged();
    partial void Onst_lnameChanging(string value);
    partial void Onst_lnameChanged();
    partial void Onst_telChanging(string value);
    partial void Onst_telChanged();
    partial void Onst_mobChanging(string value);
    partial void Onst_mobChanged();
    partial void Onst_addChanging(string value);
    partial void Onst_addChanged();
    partial void Onst_userChanging(string value);
    partial void Onst_userChanged();
    partial void Onst_passChanging(string value);
    partial void Onst_passChanged();
    #endregion
	
	public staff()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int st_id
	{
		get
		{
			return this._st_id;
		}
		set
		{
			if ((this._st_id != value))
			{
				this.Onst_idChanging(value);
				this.SendPropertyChanging();
				this._st_id = value;
				this.SendPropertyChanged("st_id");
				this.Onst_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_fname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string st_fname
	{
		get
		{
			return this._st_fname;
		}
		set
		{
			if ((this._st_fname != value))
			{
				this.Onst_fnameChanging(value);
				this.SendPropertyChanging();
				this._st_fname = value;
				this.SendPropertyChanged("st_fname");
				this.Onst_fnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_lname", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string st_lname
	{
		get
		{
			return this._st_lname;
		}
		set
		{
			if ((this._st_lname != value))
			{
				this.Onst_lnameChanging(value);
				this.SendPropertyChanging();
				this._st_lname = value;
				this.SendPropertyChanged("st_lname");
				this.Onst_lnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_tel", DbType="NVarChar(20)")]
	public string st_tel
	{
		get
		{
			return this._st_tel;
		}
		set
		{
			if ((this._st_tel != value))
			{
				this.Onst_telChanging(value);
				this.SendPropertyChanging();
				this._st_tel = value;
				this.SendPropertyChanged("st_tel");
				this.Onst_telChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_mob", DbType="NVarChar(20)")]
	public string st_mob
	{
		get
		{
			return this._st_mob;
		}
		set
		{
			if ((this._st_mob != value))
			{
				this.Onst_mobChanging(value);
				this.SendPropertyChanging();
				this._st_mob = value;
				this.SendPropertyChanged("st_mob");
				this.Onst_mobChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_add", DbType="NVarChar(300)")]
	public string st_add
	{
		get
		{
			return this._st_add;
		}
		set
		{
			if ((this._st_add != value))
			{
				this.Onst_addChanging(value);
				this.SendPropertyChanging();
				this._st_add = value;
				this.SendPropertyChanged("st_add");
				this.Onst_addChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_user", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string st_user
	{
		get
		{
			return this._st_user;
		}
		set
		{
			if ((this._st_user != value))
			{
				this.Onst_userChanging(value);
				this.SendPropertyChanging();
				this._st_user = value;
				this.SendPropertyChanged("st_user");
				this.Onst_userChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_pass", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string st_pass
	{
		get
		{
			return this._st_pass;
		}
		set
		{
			if ((this._st_pass != value))
			{
				this.Onst_passChanging(value);
				this.SendPropertyChanging();
				this._st_pass = value;
				this.SendPropertyChanged("st_pass");
				this.Onst_passChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class validmanageruserpassResult
{
	
	private int _mng_id;
	
	public validmanageruserpassResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mng_id", DbType="Int NOT NULL")]
	public int mng_id
	{
		get
		{
			return this._mng_id;
		}
		set
		{
			if ((this._mng_id != value))
			{
				this._mng_id = value;
			}
		}
	}
}

public partial class validstaffuserpassResult
{
	
	private int _st_id;
	
	public validstaffuserpassResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_id", DbType="Int NOT NULL")]
	public int st_id
	{
		get
		{
			return this._st_id;
		}
		set
		{
			if ((this._st_id != value))
			{
				this._st_id = value;
			}
		}
	}
}

public partial class validsupervisoruserpassResult
{
	
	private int _sup_id;
	
	public validsupervisoruserpassResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sup_id", DbType="Int NOT NULL")]
	public int sup_id
	{
		get
		{
			return this._sup_id;
		}
		set
		{
			if ((this._sup_id != value))
			{
				this._sup_id = value;
			}
		}
	}
}

public partial class validreceptionistuserpassResult
{
	
	private int _recep_id;
	
	public validreceptionistuserpassResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recep_id", DbType="Int NOT NULL")]
	public int recep_id
	{
		get
		{
			return this._recep_id;
		}
		set
		{
			if ((this._recep_id != value))
			{
				this._recep_id = value;
			}
		}
	}
}
#pragma warning restore 1591
